In [15]:
import numpy as np
data = np.load('results_RVE_1_40_D\DB3_GA\simulations.npy', allow_pickle=True)
data = data.tolist()
print(len(data))
i = 0
index_to_delete = [43, 44] #assuming you want to remove the second and the third elements from the dictionary
keys_to_delete = []
for key in data.keys():
    if i in index_to_delete:
        print(key)
        keys_to_delete.append(key)
    i = i + 1

for key in keys_to_delete:
    if key in data:
        del data[key]
print(data)
np.save("simulations1.npy", data)

45
(2, 149, 3, 0.5, 1.35, 2.25)
(3, 155, 2, 0.5, 1.35, 2.25)
{(2.0, 148.0, 20.0, 0.7, 1.95, 2.7): (array([-2.12660350e-18, -2.11419424e-18, -1.65730277e-07, -4.97271611e-07,
       -9.94705537e-07, -1.65811300e-06, -2.48361703e-06, -3.45086560e-06,
       -4.51989705e-06, -5.59036746e-06, -6.43959785e-06, -6.61187588e-06,
       -5.24283549e-06, -8.23427053e-07,  9.03906632e-06,  2.76990343e-05,
        5.91672932e-05,  1.07332258e-04,  1.74962566e-04,  2.63017717e-04,
        3.70619720e-04,  7.09406357e-04,  1.11420645e-03,  1.55398572e-03,
        2.01213054e-03,  2.48075049e-03,  2.95614277e-03,  3.43643890e-03,
        3.92053149e-03,  4.40762564e-03,  4.89707294e-03,  5.38832065e-03,
        5.88089990e-03,  6.37442222e-03,  6.86857399e-03,  7.36310774e-03,
        7.85783167e-03,  8.35259925e-03,  8.84729995e-03,  9.34185131e-03,
        9.83619257e-03,  1.03302795e-02,  1.08240806e-02,  1.13175737e-02,
        1.18107439e-02,  1.23035818e-02,  1.27960817e-02,  2.03879292e-02,
 

In [2]:
import numpy as np

path = "results_RVE_1_40_D/PH3_GA"
initial_data = np.load(f"{path}/initial_simulations.npy", allow_pickle=True)

initial_data = initial_data.tolist()
oldkeys = list(initial_data.keys())
# Type in i[number] to rearrange your parmeters
newkeys = list(map(lambda i: (i[3], i[2], i[0], i[1]), initial_data.keys()))
for i in range(len(newkeys)):
    initial_data[newkeys[i]] = initial_data.pop(oldkeys[i])
np.save(f"{path}/initial_simulations2.npy", initial_data)
'''
initial_data = np.load(f"{path}/simulations.npy", allow_pickle=True)

initial_data = initial_data.tolist()
oldkeys = list(initial_data.keys())
newkeys = list(map(lambda i: (i[3], i[2], i[0], i[1]), initial_data.keys()))
for i in range(len(newkeys)):
    initial_data[newkeys[i]] = initial_data.pop(oldkeys[i])
np.save(f"{path}/simulations2.npy", initial_data)
'''

'\ninitial_data = np.load(f"{path}/simulations.npy", allow_pickle=True)\n\ninitial_data = initial_data.tolist()\noldkeys = list(initial_data.keys())\nnewkeys = list(map(lambda i: (i[3], i[2], i[0], i[1]), initial_data.keys()))\nfor i in range(len(newkeys)):\n    initial_data[newkeys[i]] = initial_data.pop(oldkeys[i])\nnp.save(f"{path}/simulations2.npy", initial_data)\n'

In [16]:
params = {'a': 1, 'b': 2, 'c': 3}
np.save("dummy.npy", params)
data = np.load("dummy.npy", allow_pickle=True)
data = data.tolist()
print(data)
print(type(data))

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>


In [19]:
from copyreg import pickle
import pandas as pd
# from modules.fitness import *
# from modules.helper import *
data = np.load("results_RVE_1_40_D\DB2_GA\initial_simulations2.npy", allow_pickle=True).tolist()
exp_curve = pd.read_csv(f'targets_RVE_1_40_D\DB2.csv')   # <--- Target curve file path.
exp_stress = exp_curve.iloc[:,0] # Getting the experimental stress
exp_strain = exp_curve.iloc[:,1] # Getting the experimental strain
def calculateIndex(stress, strain):
    i = 0
    while strain[i] <= 0.002:
        i += 1
    return stress[i]
expYieldStress = calculateIndex(exp_stress, exp_strain)
print(expYieldStress)
# y = np.array([interpolatedStressFunction(simStress, simStrain, interpolatedStrain) * convertUnit for (simStrain, simStress) in sim.simulations.values()])
# zipParamsStress = list(zip(list(sim.simulations.keys()), y))
sortedClosestYieldStress = list(sorted(data.items(), key=lambda pairs: abs(calculateIndex(pairs[1][1], pairs[1][0]) - expYieldStress)))
sortedClosestYieldStress = dict(sortedClosestYieldStress[:30])
print(len(sortedClosestYieldStress))
print(type(sortedClosestYieldStress))
print(sortedClosestYieldStress)
data = np.save("initial_simulations2.npy", sortedClosestYieldStress)

106305634.426
30
<class 'dict'>
{(0.75, 76.0, 0.37, 0.28, 1.75, 1.9): (array([-2.12660350e-18, -2.14129929e-18, -1.65730280e-07, -4.97271614e-07,
       -5.01908691e-07,  9.61517154e-06,  5.36930162e-05,  1.43856183e-04,
        2.72187058e-04,  4.25373520e-04,  5.93400016e-04,  7.70300208e-04,
        9.52772153e-04,  1.13897428e-03,  1.32781692e-03,  1.51859929e-03,
        1.71083409e-03,  1.90416302e-03,  2.09831417e-03,  2.29307814e-03,
        2.48829294e-03,  2.97754942e-03,  3.46762664e-03,  3.95786417e-03,
        4.44793385e-03,  4.93767916e-03,  5.42703183e-03,  5.91596879e-03,
        6.40448986e-03,  6.89260600e-03,  7.38033318e-03,  7.86768902e-03,
        8.35469104e-03,  8.84135582e-03,  9.32769862e-03,  9.81373323e-03,
        1.02994720e-02,  1.07849261e-02,  1.12701051e-02,  1.17550178e-02,
        1.22396718e-02,  1.27240737e-02,  1.32082296e-02,  1.36921447e-02,
        1.41758235e-02,  1.46592701e-02,  1.51424882e-02,  2.26047123e-02,
        3.00173098e-02,  3.73

In [21]:
import pandas as pd
data = np.load("results_RVE_1_40_D\DB2_GA\initial_simulations.npy", allow_pickle=True).tolist()
params = np.array(list(data.keys()))
print(params)
np.save("DB2.npy", params)

[[7.50e-01 7.60e+01 3.70e-01 2.80e-01 1.75e+00 1.90e+00]
 [8.20e-01 5.20e+01 7.00e-01 2.00e-01 1.50e+00 2.85e+00]
 [4.40e-01 9.10e+01 6.00e-01 3.40e-01 1.65e+00 1.20e+00]
 [1.40e-01 1.00e+02 8.50e-01 2.70e-01 1.25e+00 1.05e+00]
 [4.30e-01 5.30e+01 4.10e-01 3.10e-01 1.65e+00 1.50e+00]
 [7.00e-01 9.00e+01 6.40e-01 2.80e-01 1.25e+00 1.00e+00]
 [4.70e-01 9.50e+01 9.00e-01 3.60e-01 1.55e+00 1.00e+00]
 [6.00e-02 7.70e+01 1.90e-01 1.70e-01 1.30e+00 2.45e+00]
 [2.00e-02 5.20e+01 4.40e-01 2.50e-01 1.85e+00 2.10e+00]
 [9.50e-01 6.60e+01 5.50e-01 2.30e-01 1.60e+00 1.75e+00]
 [6.00e-01 9.20e+01 6.80e-01 1.90e-01 1.30e+00 1.50e+00]
 [4.00e-01 6.30e+01 2.70e-01 2.40e-01 1.45e+00 1.05e+00]
 [9.80e-01 6.50e+01 9.60e-01 2.30e-01 1.75e+00 1.95e+00]
 [8.70e-01 6.50e+01 1.70e-01 2.40e-01 1.95e+00 2.30e+00]
 [5.10e-01 6.60e+01 9.50e-01 2.10e-01 1.70e+00 2.25e+00]
 [9.80e-01 9.40e+01 5.20e-01 1.80e-01 1.00e+00 1.65e+00]
 [9.00e-01 9.10e+01 2.70e-01 3.10e-01 1.85e+00 2.50e+00]
 [8.40e-01 9.70e+01 7.20e-01 1.

In [5]:
print(tuple(i * 10 for i in (1,2)))
print(10 ** -2)
print(10 ** 2)

(10, 20)
0.01
100


In [14]:
import numpy as np
dictResult = {'dipole': 3, 'islip': 146, 'omega': 3, 'p': 0.5, 'q': 1.35, 'tausol': 2.25}
np.save("full_result", dictResult) 