In [8]:
import numpy as np
data = np.load('DB3.npy', allow_pickle=True)
data = data.tolist()
print(data)

[[2.0, 148.0, 20.0, 0.7, 1.95, 2.7], [2.0, 193.0, 22.0, 0.25, 1.45, 1.15], [1.0, 109.0, 44.0, 0.35, 1.6, 1.8], [9.0, 143.0, 28.0, 0.6, 1.75, 1.55], [4.0, 189.0, 46.0, 0.15, 1.8, 2.3], [7.0, 150.0, 44.0, 0.35, 2.0, 1.85], [11.0, 118.0, 26.0, 0.1, 1.2, 1.9], [13.0, 135.0, 9.0, 0.25, 1.25, 1.35], [24.0, 198.0, 30.0, 0.1, 1.2, 1.45], [13.0, 170.0, 11.0, 0.1, 1.8, 2.25], [9.0, 153.0, 41.0, 0.1, 1.4, 1.05], [4.0, 110.0, 42.0, 0.15, 1.15, 2.2], [10.0, 130.0, 45.0, 0.5, 1.75, 1.1], [16.0, 182.0, 42.0, 0.2, 1.1, 1.0], [7.0, 144.0, 46.0, 0.3, 1.9, 1.9], [2.0, 119.0, 33.0, 0.85, 1.05, 2.55], [7.0, 192.0, 33.0, 0.7, 1.75, 1.9], [5.0, 144.0, 50.0, 0.45, 1.85, 2.5], [8.0, 135.0, 25.0, 0.75, 1.6, 1.75], [1.0, 106.0, 44.0, 0.1, 1.1, 1.55], [3.0, 112.0, 34.0, 0.1, 1.65, 2.05], [21.0, 176.0, 16.0, 0.2, 1.75, 2.95], [15.0, 186.0, 26.0, 0.75, 1.95, 1.2], [10.0, 164.0, 17.0, 0.6, 1.65, 2.8], [11.0, 183.0, 19.0, 0.8, 1.35, 1.15], [17.0, 168.0, 18.0, 0.3, 1.55, 2.0], [1.0, 197.0, 22.0, 0.3, 1.7, 1.65], [7.0,

In [2]:
import numpy as np

path = "results_RVE_1_40_D/PH3_GA"
initial_data = np.load(f"{path}/initial_simulations.npy", allow_pickle=True)

initial_data = initial_data.tolist()
oldkeys = list(initial_data.keys())
# Type in i[number] to rearrange your parmeters
newkeys = list(map(lambda i: (i[3], i[2], i[0], i[1]), initial_data.keys()))
for i in range(len(newkeys)):
    initial_data[newkeys[i]] = initial_data.pop(oldkeys[i])
np.save(f"{path}/initial_simulations2.npy", initial_data)
'''
initial_data = np.load(f"{path}/simulations.npy", allow_pickle=True)

initial_data = initial_data.tolist()
oldkeys = list(initial_data.keys())
newkeys = list(map(lambda i: (i[3], i[2], i[0], i[1]), initial_data.keys()))
for i in range(len(newkeys)):
    initial_data[newkeys[i]] = initial_data.pop(oldkeys[i])
np.save(f"{path}/simulations2.npy", initial_data)
'''

'\ninitial_data = np.load(f"{path}/simulations.npy", allow_pickle=True)\n\ninitial_data = initial_data.tolist()\noldkeys = list(initial_data.keys())\nnewkeys = list(map(lambda i: (i[3], i[2], i[0], i[1]), initial_data.keys()))\nfor i in range(len(newkeys)):\n    initial_data[newkeys[i]] = initial_data.pop(oldkeys[i])\nnp.save(f"{path}/simulations2.npy", initial_data)\n'

In [16]:
params = {'a': 1, 'b': 2, 'c': 3}
np.save("dummy.npy", params)
data = np.load("dummy.npy", allow_pickle=True)
data = data.tolist()
print(data)
print(type(data))

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>


In [19]:
from copyreg import pickle
import pandas as pd
# from modules.fitness import *
# from modules.helper import *
data = np.load("results_RVE_1_40_D\DB2_GA\initial_simulations2.npy", allow_pickle=True).tolist()
exp_curve = pd.read_csv(f'targets_RVE_1_40_D\DB2.csv')   # <--- Target curve file path.
exp_stress = exp_curve.iloc[:,0] # Getting the experimental stress
exp_strain = exp_curve.iloc[:,1] # Getting the experimental strain
def calculateIndex(stress, strain):
    i = 0
    while strain[i] <= 0.002:
        i += 1
    return stress[i]
expYieldStress = calculateIndex(exp_stress, exp_strain)
print(expYieldStress)
# y = np.array([interpolatedStressFunction(simStress, simStrain, interpolatedStrain) * convertUnit for (simStrain, simStress) in sim.simulations.values()])
# zipParamsStress = list(zip(list(sim.simulations.keys()), y))
sortedClosestYieldStress = list(sorted(data.items(), key=lambda pairs: abs(calculateIndex(pairs[1][1], pairs[1][0]) - expYieldStress)))
sortedClosestYieldStress = dict(sortedClosestYieldStress[:30])
print(len(sortedClosestYieldStress))
print(type(sortedClosestYieldStress))
print(sortedClosestYieldStress)
data = np.save("initial_simulations2.npy", sortedClosestYieldStress)

106305634.426
30
<class 'dict'>
{(0.75, 76.0, 0.37, 0.28, 1.75, 1.9): (array([-2.12660350e-18, -2.14129929e-18, -1.65730280e-07, -4.97271614e-07,
       -5.01908691e-07,  9.61517154e-06,  5.36930162e-05,  1.43856183e-04,
        2.72187058e-04,  4.25373520e-04,  5.93400016e-04,  7.70300208e-04,
        9.52772153e-04,  1.13897428e-03,  1.32781692e-03,  1.51859929e-03,
        1.71083409e-03,  1.90416302e-03,  2.09831417e-03,  2.29307814e-03,
        2.48829294e-03,  2.97754942e-03,  3.46762664e-03,  3.95786417e-03,
        4.44793385e-03,  4.93767916e-03,  5.42703183e-03,  5.91596879e-03,
        6.40448986e-03,  6.89260600e-03,  7.38033318e-03,  7.86768902e-03,
        8.35469104e-03,  8.84135582e-03,  9.32769862e-03,  9.81373323e-03,
        1.02994720e-02,  1.07849261e-02,  1.12701051e-02,  1.17550178e-02,
        1.22396718e-02,  1.27240737e-02,  1.32082296e-02,  1.36921447e-02,
        1.41758235e-02,  1.46592701e-02,  1.51424882e-02,  2.26047123e-02,
        3.00173098e-02,  3.73

In [21]:
import pandas as pd
data = np.load("results_RVE_1_40_D\DB2_GA\initial_simulations.npy", allow_pickle=True).tolist()
params = np.array(list(data.keys()))
print(params)
np.save("DB2.npy", params)

[[7.50e-01 7.60e+01 3.70e-01 2.80e-01 1.75e+00 1.90e+00]
 [8.20e-01 5.20e+01 7.00e-01 2.00e-01 1.50e+00 2.85e+00]
 [4.40e-01 9.10e+01 6.00e-01 3.40e-01 1.65e+00 1.20e+00]
 [1.40e-01 1.00e+02 8.50e-01 2.70e-01 1.25e+00 1.05e+00]
 [4.30e-01 5.30e+01 4.10e-01 3.10e-01 1.65e+00 1.50e+00]
 [7.00e-01 9.00e+01 6.40e-01 2.80e-01 1.25e+00 1.00e+00]
 [4.70e-01 9.50e+01 9.00e-01 3.60e-01 1.55e+00 1.00e+00]
 [6.00e-02 7.70e+01 1.90e-01 1.70e-01 1.30e+00 2.45e+00]
 [2.00e-02 5.20e+01 4.40e-01 2.50e-01 1.85e+00 2.10e+00]
 [9.50e-01 6.60e+01 5.50e-01 2.30e-01 1.60e+00 1.75e+00]
 [6.00e-01 9.20e+01 6.80e-01 1.90e-01 1.30e+00 1.50e+00]
 [4.00e-01 6.30e+01 2.70e-01 2.40e-01 1.45e+00 1.05e+00]
 [9.80e-01 6.50e+01 9.60e-01 2.30e-01 1.75e+00 1.95e+00]
 [8.70e-01 6.50e+01 1.70e-01 2.40e-01 1.95e+00 2.30e+00]
 [5.10e-01 6.60e+01 9.50e-01 2.10e-01 1.70e+00 2.25e+00]
 [9.80e-01 9.40e+01 5.20e-01 1.80e-01 1.00e+00 1.65e+00]
 [9.00e-01 9.10e+01 2.70e-01 3.10e-01 1.85e+00 2.50e+00]
 [8.40e-01 9.70e+01 7.20e-01 1.

In [5]:
print(tuple(i * 10 for i in (1,2)))
print(10 ** -2)
print(10 ** 2)

(10, 20)
0.01
100
