In [3]:
# External libraries
import pandas as pd
import numpy as np

In [6]:
params1 = pd.read_excel(f"DB_RVE_14_0_D_converging_params.xlsx" , skiprows= 8, nrows=30, usecols = "A:F").to_numpy()
params2 = pd.read_excel(f"DB_RVE_14_0_D_converging_params.xlsx" , skiprows= 8, nrows=30, usecols = "H:M").to_numpy()
params3 = pd.read_excel(f"DB_RVE_14_0_D_converging_params.xlsx" , skiprows= 8, nrows=30, usecols = "O:T").to_numpy()
print(params1)
np.save(f'DB1.npy', params1)
np.save(f'DB2.npy', params1)
np.save(f'DB3.npy', params1)
# To use them, copy these part to convert them to a list of tuples
# manualParams1 = np.load(f'manualParams/manualParams1.npy', allow_pickle=True)
# manualParams1 = list(map(lambda x: tuple(x), params1))

[[7.00e+00 3.50e+01 2.10e+01 2.00e-01 1.65e+00 6.00e-02]
 [9.00e+00 3.00e+01 3.00e+01 3.00e-01 1.25e+00 1.90e-01]
 [3.00e+00 1.70e+01 8.00e+00 3.00e-01 1.55e+00 2.00e-02]
 [8.00e+00 3.30e+01 2.60e+01 8.50e-01 2.00e+00 3.30e-01]
 [4.00e+00 1.80e+01 1.00e+00 9.00e-01 1.65e+00 3.40e-01]
 [5.00e+00 2.60e+01 1.00e+01 7.00e-01 1.70e+00 1.70e-01]
 [6.00e+00 3.60e+01 1.00e+01 7.00e-01 1.80e+00 3.80e-01]
 [1.10e+01 4.40e+01 8.00e+00 9.50e-01 1.10e+00 3.90e-01]
 [8.00e+00 2.60e+01 3.80e+01 4.50e-01 1.50e+00 1.90e-01]
 [1.00e+01 5.00e+01 3.80e+01 1.50e-01 1.85e+00 2.10e-01]
 [4.00e+00 3.70e+01 2.50e+01 2.50e-01 2.00e+00 2.80e-01]
 [6.00e+00 4.20e+01 9.00e+00 9.50e-01 1.60e+00 1.20e-01]
 [2.00e+00 3.70e+01 7.00e+00 8.50e-01 1.55e+00 3.40e-01]
 [7.00e+00 4.90e+01 4.00e+01 4.00e-01 1.75e+00 1.30e-01]
 [3.00e+00 3.00e+01 4.20e+01 2.50e-01 1.60e+00 1.90e-01]
 [3.00e+00 3.60e+01 5.00e+01 6.00e-01 1.20e+00 4.50e-01]
 [3.30e+01 2.90e+01 2.00e+00 3.50e-01 2.00e+00 7.00e-02]
 [4.00e+00 2.80e+01 1.60e+01 6.