In [6]:
# External libraries
import pandas as pd
import numpy as np

In [8]:
params1 = pd.read_excel(f"DB_RVE_14_0_D_converging_params.xlsx" , skiprows= 8, nrows=30, usecols = "A:F").to_numpy()
params2 = pd.read_excel(f"DB_RVE_14_0_D_converging_params.xlsx" , skiprows= 8, nrows=60, usecols = "H:M").to_numpy()
params3 = pd.read_excel(f"DB_RVE_14_0_D_converging_params.xlsx" , skiprows= 8, nrows=30, usecols = "O:T").to_numpy()
np.save(f'DB1.npy', params1)
np.save(f'DB2.npy', params2)
np.save(f'DB3.npy', params3)
# To use them, copy these part to convert them to a list of tuples
# manualParams1 = np.load(f'DB1.npy', allow_pickle=True)
# print(manualParams1)
manualParams2 = np.load(f'DB2.npy', allow_pickle=True)
print(manualParams2)
# manualParams3 = np.load(f'DB3.npy', allow_pickle=True)
# print(manualParams3)

[[7.90e-01 7.50e+01 8.60e-01 1.50e-01 1.80e+00 2.10e+00]
 [3.20e-01 5.40e+01 7.10e-01 1.30e-01 1.95e+00 1.40e+00]
 [9.00e-01 9.10e+01 2.70e-01 3.10e-01 1.85e+00 2.50e+00]
 [8.80e-01 5.80e+01 1.30e-01 1.30e-01 1.65e+00 2.45e+00]
 [7.30e-01 9.70e+01 5.20e-01 1.40e-01 1.45e+00 1.20e+00]
 [6.70e-01 5.60e+01 3.30e-01 2.00e-01 2.00e+00 1.70e+00]
 [3.50e-01 9.10e+01 2.40e-01 3.30e-01 1.60e+00 2.95e+00]
 [8.20e-01 5.20e+01 7.00e-01 2.00e-01 1.50e+00 2.85e+00]
 [1.40e-01 1.00e+02 8.50e-01 2.70e-01 1.25e+00 1.05e+00]
 [2.50e-01 5.70e+01 7.20e-01 5.00e-01 1.90e+00 1.55e+00]
 [9.50e-01 6.60e+01 5.50e-01 2.30e-01 1.60e+00 1.75e+00]
 [4.50e-01 6.10e+01 1.60e-01 1.70e-01 2.00e+00 1.60e+00]
 [4.70e-01 6.40e+01 9.70e-01 4.20e-01 1.55e+00 2.95e+00]
 [3.40e-01 9.30e+01 8.10e-01 3.70e-01 1.80e+00 2.95e+00]
 [4.00e-02 9.50e+01 5.30e-01 4.80e-01 1.00e+00 1.90e+00]
 [9.00e-01 8.70e+01 3.00e-02 2.60e-01 1.05e+00 1.90e+00]
 [8.70e-01 7.80e+01 6.60e-01 3.90e-01 2.00e+00 2.75e+00]
 [2.00e-01 7.10e+01 8.60e-01 1.